__Лабораторная работа №19__

Рассчитайте метрики TF-IDF для любых 3 песен на одном языке,   
которые вы сами выберите.

Не забудьте, что нужно привести слова к начальной форме, убрать стоп-слова.

---

Rolling Stones - Paint it Black
[![YouTube](https://img.youtube.com/vi/niCG-LDrN9Q/1.jpg)](https://www.youtube.com/watch?v=niCG-LDrN9Q)


https://music.yandex.ru/translate/track/1703893

Creedence - Suzie Q.  
[![YouTube](https://img.youtube.com/vi/18kqUNG9mO4/1.jpg)](https://www.youtube.com/watch?v=18kqUNG9mO4)

https://music.yandex.ru/translate/track/37408169

The Doors - Riders on the Storm  
[![YouTube](https://img.youtube.com/vi/iPRSxwZBmcM/1.jpg)](https://www.youtube.com/watch?v=iPRSxwZBmcM)

https://music.yandex.ru/translate/track/985760

The Doors - People Are Strange 
[![YouTube](https://img.youtube.com/vi/AgHaGrZkkv4/2.jpg)](https://www.youtube.com/watch?v=AgHaGrZkkv4)

https://music.yandex.ru/translate/track/17190963

Black Sabbath - Paranoid   
[![YouTube](https://img.youtube.com/vi/0qanF-91aJo/2.jpg)](https://www.youtube.com/watch?v=0qanF-91aJo)

https://music.yandex.ru/translate/track/645247

---

In [1]:
import requests
from requests.exceptions import HTTPError
from bs4 import BeautifulSoup
import sys
import logging
import pandas as pd

In [2]:
logging.basicConfig(
    format=u'[%(levelname)-8s] %(asctime)s | %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S',
    level=logging.INFO,
    # level=logging.DEBUG,
    stream=sys.stdout,
)
   
pd.set_option('max_colwidth',0)   
pd.set_option('display.precision', 2)

## качаем данные

In [3]:
# список ссылок на тексты
links = {
    'Rolling Stones - Paint it BlackYouTube': 'https://music.yandex.ru/translate/track/1703893',
    'Creedence - Suzie Q.': 'https://music.yandex.ru/translate/track/37408169',
    'The Doors - Riders on the Storm': 'https://music.yandex.ru/translate/track/985760',
    'Black Sabbath - Paranoid': 'https://music.yandex.ru/translate/track/645247',
'The Doors - People Are Strange': 'https://music.yandex.ru/translate/track/17190963',
}

In [4]:
class HttpGetRequest:

    def __init__( self, header_params=None, ):
        self._header_params = header_params
        
    def get(self, url, params=None):
        try:
            response = requests.get(url,headers=self._header_params,params=params,)
            response.raise_for_status() 
            logging.debug('HttpGetRequest: request success')
            return response

        except HTTPError as http_err:
            logging.error(f'HttpGetRequest: request : {http_err}')

        except Exception as err:
            logging.error(f'HttpGetRequest: request : {err}')

        return ''    


class YandexSongDownloader(HttpGetRequest):
    
    def __init__( self ):
        # header_params = {  'x-auth-token': token, 'Content-Type': 'application/x-www-form-urlencoded', }  
        header_params = {
             'Content-Type':'text/html; charset=utf-8', 
             'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0',
             }
        super().__init__(header_params=header_params)
        
        
    def get(self,url):
            
        return  (
            BeautifulSoup( super().get(url).text, "html.parser")
            .find('div', class_='container song-text')
            .find('pre')
            .text
        )

In [5]:
# качаем тексты
data = pd.DataFrame({
        t: [  YandexSongDownloader().get(links[t]), ]
        for t in links
    }).T
data.columns = ['text']

display(data)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                text
Rolling Stones - Paint it BlackYouTube  I see a red door and I want it painted black\nNo colors anymore I want them to turn black\nI see the girls walk by dressed in their summer clothes\nI have to turn my head until my darkness goes\n\nI see a line of cars and they're all painted black\nWith flowers and my love both never to come back\nI see people turn their heads and quickly look away\nLike a new born baby it just happens every day\n\nI look inside myself and see my heart is black\nI see my red door and it has been painted black\nMaybe then I'll fade away and not have to face the facts\nIt's not easy facin' up when your whole world is black\n\nNo more will my green sea go turn a deeper blue\nI could not foresee this thing happening to you\nIf I look hard enough into the settin' sun\nMy love will laugh with me before the mornin' comes\n\nI see a red door and I want it painted black\nNo colors anymore I want them to turn black\nI see the girls walk by dressed in their summer clothes\nI have to turn my head until my darkness goes\n\nI wanna see it painted, painted black\nBlack as night, black as coal\nI wanna see the sun blotted out from the sky\nI wanna see it painted, painted, painted, painted black
Creedence - Suzie Q.                    Oh Suzie Q\nOh Suzie Q\nOh Suzie Q Baby I love you\nSuzie Q\nI like the way you walk\nI like the way you talk\nI like the way you walk I like the way you talk\nSuzie Q\n(Guitar solo)\nOh say that you? ll be true\nOh say that you? ll be true\nOh say that you? ll be true and never leave me blue\nSuzie Q\nOh say that you? ll be mine\nOh say that you? ll be mine\nOh say that you? ll be mine Baby all the time\nSuzie Q\n(Guitar solo)\nOh, Suzie Q\nOh, Suzie Q\nOh, Suzie Q, Baby, I love you\nSuzie Q\nI like the way you walk\nI like the way you talk\nI like the way you walk, I like the way you talk\nSuzie Q\nOh, Suzie Q\nOh, Suzie Q\nOh, Suzie Q, Baby, I love you\nSuzie Q\n(Guitar solo to end)
The Doors - Riders on the Storm         Riders on the storm, riders on the storm\nInto this house we’re born, into this world we’re thrown\nLike a dog without a bone, an actor out on loan\nRiders on the storm\nThere’s a killer on the road, his brain is squirmin' like a toad\nTake a long holiday, let your children play\nIf ya give this man a ride, sweet family will die\nKiller on the road, yeah\nGirl ya gotta love your man, girl ya gotta love your man\nTake him by the hand, make him understand\nThe world on you depends, our life will never end\nGotta love your man, yeah\nRiders on the storm, riders on the storm\nInto this house we’re born, into this world we’re thrown\nLike a dog without a bone, an actor out on loan\nRiders on the storm\nRiders on the storm, riders on the storm\nRiders on the storm, riders on the storm
Black Sabbath - Paranoid                Finished with my woman 'cause she couldn't help me with my mind,\nPeople think I'm insane because I am frowning all the time,\nAll day long I think of things but nothing seems to satisfy,\nThink I'll lose my mind if I don't find something to pacify,\nCan you help me occupy my brain?\nOh yeah\n\nI need someone to show me the things in life that I can't find,\nI can't see the things that make true happiness, I must be blind,\nMake a joke and I will sigh and you will laugh and I will cry,\nHappiness I cannot feel and love to me us so unreal\nAnd so as you hear these words telling you now of my state\nI tell you to enjoy life I wish I could but it's too late
The Doors - People Are Strange          People are strange when you're a stranger\nFaces look ugly when you're alone\nWomen seem wicked when you're unwanted\nStreets are uneven when you're down\nWhen you're strange\nFaces come out of the rain\nWhen you're strange\nNo one remembers your name\nWhen you're strange\nWhen you're strange\nWhen you're strange\nPeople are strange when you're a stranger\nFaces look ugly when you're alone\nWomen seem wicked when you're unwanted\nStreets are uneven when you're down\nWhen you're strange\nFaces come out of the rain\nWhen you're strange\nNo one remembers your name\nWhen you're strange\nWhen you're strange\nWhen you're strange\nWhen you're strange\nFaces come out of the rain\nWhen you're strange\nNo one remembers your name\nWhen you're strange\nWhen you're strange\nWhen you're strange

In [6]:
assert (data['text'].str.len()>1).all()

## частотный анализ

In [7]:
# токенайзер - режем текст на отдельные слова

from nltk.tokenize import word_tokenize as nltk_tokenize_word
from nltk.corpus import stopwords as nltk_stopwords
from nltk.stem import WordNetLemmatizer
import re

stopwords = set(nltk_stopwords.words('russian'))
lemmatizer = WordNetLemmatizer()

def tokenizer(text,stopwords=stopwords,lemmatizer=lemmatizer):
    return [ 
        lemmatizer.lemmatize(t)
        for t in nltk_tokenize_word( text.lower(), language='english' ) 
        if (t not in stopwords) and ( re.match(r'^[A-z]{3,}$',t) ) 
    ]

In [8]:
# рисуем таблицу результата
def tf_table(x,v,d):
    print( 'словарь:', len(v), 'слов\n') 
    return pd.concat([ 
        pd.DataFrame(x,columns=v), 
        pd.Series(d,name='Song')
    ],axis=1).set_index('Song')

---

In [9]:
# простой частотный анализ - считаем слова

from sklearn.feature_extraction.text import CountVectorizer

tf_model = CountVectorizer(
        tokenizer=tokenizer, # ф-ция токенайзер
        token_pattern=None, # отключаем дефолтный токенайзер
    ).fit(data['text'])

tf_table(
        x = tf_model.transform(data['text']).todense(),
        v = sorted( tf_model.vocabulary_.keys() ),
        d=data.index
    )  # .style.background_gradient(cmap='plasma', )

словарь: 195 слов

,actor,all,alone,and,anymore,are,away,baby,back,because,...,will,wish,with,without,woman,word,world,yeah,you,your
Song,,,,,,,,,,,,,,,,,,,,,
Rolling Stones - Paint it BlackYouTube,0,1,0,8,2,0,2,1,1,0,...,2,0,2,0,0,0,1,0,1,1
Creedence - Suzie Q.,0,1,0,1,0,0,0,4,0,0,...,0,0,0,0,0,0,0,0,17,0
The Doors - Riders on the Storm,2,0,0,0,0,0,0,0,0,0,...,2,0,0,2,0,0,3,2,1,4
Black Sabbath - Paranoid,0,2,0,5,0,0,0,0,0,1,...,3,1,2,0,1,1,0,1,5,0
The Doors - People Are Strange,0,0,2,0,0,4,0,0,0,0,...,0,0,0,0,2,0,0,0,23,3

----

In [10]:
# частотный анализ с нормализацией и обратной частотой (TF-IDF)

from sklearn.feature_extraction.text import TfidfVectorizer

# использования токенайзера вместе с векторайзером
tf_model = TfidfVectorizer(
        min_df=.01, # выкидываем очень редкие слова
        max_df=.50, # выкидываем очень частые слова
        use_idf=True, # используем обратную частоту
        norm='l2', # нормируем TF
        tokenizer=tokenizer, # ф-ция токенайзер
        token_pattern=None, # отключаем дефолтный токенайзер
    ).fit( data['text'] )


tf_table(
    x = tf_model.transform(data['text']).todense(),
    v = sorted( tf_model.vocabulary_.keys() ),
    d=data.index
)

словарь: 184 слов

,actor,alone,anymore,are,away,baby,back,because,been,before,...,when,whole,wicked,wish,with,without,woman,word,world,yeah
Song,,,,,,,,,,,,,,,,,,,,,
Rolling Stones - Paint it BlackYouTube,0.00,0.00,0.09,0.00,0.09,0.03,0.04,0.0,0.04,0.04,...,0.03,0.04,0.00,0.0,0.07,0.00,0.00,0.0,0.03,0.00
Creedence - Suzie Q.,0.00,0.00,0.00,0.00,0.00,0.15,0.00,0.0,0.00,0.00,...,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,0.00,0.00
The Doors - Riders on the Storm,0.11,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,...,0.00,0.00,0.00,0.0,0.00,0.11,0.00,0.0,0.13,0.09
Black Sabbath - Paranoid,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.1,0.00,0.00,...,0.00,0.00,0.00,0.1,0.17,0.00,0.08,0.1,0.00,0.08
The Doors - People Are Strange,0.00,0.07,0.00,0.15,0.00,0.00,0.00,0.0,0.00,0.00,...,0.68,0.00,0.07,0.0,0.00,0.00,0.06,0.0,0.00,0.00